FROM node:18.19.0 as base

WORKDIR /home/app/coupon

ENV PATH /home/app/coupon/node_modules/.bin:$PATH

COPY package*.json ./
COPY .npmrc ./

RUN npm install --location=global npm@9.3.1
RUN npm install --location=global react-scripts
RUN npm install --legacy-peer-deps
RUN npm run types

COPY . .


